#pragma config(UART_Usage, UART2, uartUserControl, baudRate4800, IOPins, None, None)
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           loader,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           flyWheel,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Drive Train and Autonomous VEX 2018/2019              */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"

//stop everything
	void stopAll(){
		motor[rightMotor] = 0;
		motor[leftMotor] = 0;
		motor[loader] = 0;
		motor[flyWheel] = 0;
	}

//Drive forward
	void driveForward (){
			motor[rightMotor] = 127;
			motor[leftMotor] = 127;
	}
//Drive backward
	void driveBackward (){
			motor[rightMotor] = -127;
			motor[leftMotor] = -127;
	}

//Left Point Turn
	void leftPoint () {
		motor[rightMotor] = 127;
		motor[leftMotor] = -127;
	}

//Right Point Turn
	void rightPoint () {
		motor[rightMotor] = -127;
		motor[leftMotor] = 127;
	}
//Need to Do More on this!!
	void auto() {
		leftPoint();
		wait1Msec(300);
		driveForward();
		wait1Msec(3000);
		rightPoint();
		wait1Msec(400);
		driveForward();
		wait1Msec(2650);
		rightPoint();
		wait1Msec(250);
		driveForward();
		wait1Msec(1800);
		driveBackward();
		wait1Msec(100);
		stopAll();
	}

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*---------------------------------------------------------------------------*/

//I have no Idea what this is for but I won't delete it yet

	void pre_auton() {
	  bStopTasksBetweenModes = true;
	}

	task autonomous() {
	auto();
	}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*---------------------------------------------------------------------------*/

//user control and Movement Function
	//task movement() {
	//Shooting Variables
		int i = 50

	task usercontrol() {
		while(true) {

		//Move Left Wheel
			if((vexRT[Ch3] > 15) || (vexRT[Ch3] < -15)){
				motor[leftMotor] = vexRT[Ch3];
			}
			else {
				motor[leftMotor] = 0;
			}

		//Move Right Wheel
			if((vexRT[Ch2] > 15) || (vexRT[Ch2] < -15)){
				motor[rightMotor] = vexRT[Ch2];
			}
			else {
				motor[rightMotor] = 0;
			}
//Shooting
		//Flywheel Code

			if (vexRT[Btn6U] == 1) {
				motor[flyWheel] = i;
				if (i < 127) {
					i++;
					wait1Msec(80);
				}
			}
			//if (vexRT[Btn6U] == 0) {
			//	motor[flyWheel] = 0;
			//	i = 0;
			//}
			if (vexRT[Btn6D] == 1) {
				motor[flyWheel] = i;
				if (i < 64) {
					i++;
					wait1Msec(80);
				}
			}
			if (vexRT[Btn6D] == 0 && vexRT[Btn6U] == 0) {
				motor[flyWheel] = 0;
				i = 50
			}

//Try a different Controller
		/*
			if (vexRT[Btn6U] == 1) {
				motor[flyWheel] = 64;
			}
			//if (vexRT[Btn5U] == 0) {
			//	motor[loader] = 0;
			//}
			if (vexRT[Btn6D] == 1){
				motor[flyWheel] = -64;
			}
			if (vexRT[Btn6D] == 0 && vexRT[Btn6U] == 0) {
				motor[flyWheel] = 0;
			}
		*/
	//Loader Code
			if (vexRT[Btn5U] == 1) {
				motor[loader] = 64;
			}
			/*if (vexRT[Btn5U] == 0) {
				motor[loader] = 0;
			}*/
			if (vexRT[Btn5D] == 1){
				motor[loader] = -64;
			}
			if (vexRT[Btn5D] == 0 && vexRT[Btn5U] == 0) {
				motor[loader] = 0;
			}
	}
}

	/*task main() {
		//auto();
		startTask(movement);
		startTask(shooting);
		startTask(stopEverything);
	}*/
